### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by DragonHacker1** [AllTheMods/ServerStarter#2]
Hello, your script is very great for everyone, but you not specificed how build, but i tried to build, gradle failed for me with this error "
* What went wrong:
A problem occurred evaluating root project 'serverstarter'.
> secrets.properties (The system cannot find the file specified)"
Sorry if im new here, thank you for helping.

**Comment by BloodWorkXGaming** [comment]
Pull again and try now ^^

**Comment by DragonHacker1** [comment]
fixed, thank you for solution, i have some question, why you not upload builded version? that someone build?

**Comment by BloodWorkXGaming** [comment]
There are prebuilt versions:

https://github.com/AllTheMods/ServerStarter/releases
